# Generated by Django 4.2.5 on 2023-10-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Room ID"
                    ),
                ),
                (
                    "num_seats",
                    models.IntegerField(default=0, verbose_name="Max Number of Seats"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "res_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Reservation ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                ("member_id", models.IntegerField(null=True, verbose_name="Member ID")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.room"
                    ),
                ),
            ],
        ),
    ]
