# Generated by Django 4.2.5 on 2023-10-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Room ID"
            ),
        ),
    ]
